apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
    version: v2
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy
#  type: LoadBalancer    
